name: Terraform AWS Academy Deploy Test

on:
  push:
    branches: [ main ]
    paths: 
      - 'src/**'
##teste para ver o que acontece kkkkkddssasdddd

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
        
    - name: Terraform Init
      working-directory: src/terraform
      run: terraform init
      
    - name: Terraform Validate
      working-directory: src/terraform
      run: terraform validate
      
    - name: Terraform Plan
      working-directory: src/terraform
      run: terraform plan -out=tfplan
      
    - name: Terraform Apply (Push)
      if: github.event_name == 'push'
      working-directory: src/terraform
      run: terraform apply -auto-approve
  